apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jjtkgr0px-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jjtkgr0px-python 
  name: jjtkgr0px-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jjtkgr0px-python 
